@startuml

autonumber
participant "LIBCS UI" as UI
participant "LIBCS - models" as API
participant ":modelController" as BC
participant ":modelService" as BS
participant ":modelPermissionService" as BPS
participant ":modelRepo" as BR
participant ":modelPermissionRepo" as BPR
participant ":modelMap" as BM
participant ":modelPermissionMap" as BPM
participant ":modelDTO" as DTO
participant ":modelPermissionDTO" as mDTO
participant "m:model" as B
participant "mp:modelPermission" as BP
participant ":modelSchema" as BSchema
participant ":modelPermissionSchema" as BPSchema


activate UI
activate API
UI -> API : .get('model/[doctor/imagiologist]/:id')
API -> BC : getModelsByDoctorId(req, res, next)
activate BC
BC -> BC : doctorId = req.params.id;
BC -> BPS : models = getModelPermissionByDoctorId(doctorId)
activate BPS
BPS -> BPR : modelPermissions = findByDoctorId(doctorId)
activate BPR
BPR -> BPSchema : persistence = find(query)
activate BPSchema
BPSchema --> BPR : persistence
deactivate BPSchema
loop
BPR -> BPM : permissions = toDomain(persistence)
activate BPM
BPM -> BP : create()
activate BP
BP --> BPM : modelPermission
deactivate BP
BPM --> BPR : modelPermission
deactivate BPM
end
BPR --> BPS : modelPermissions
deactivate BPR
loop
BPS -> BPM : permissions = toDTO(modelPermissions)
activate BPM
BPM -> mDTO : create()
activate mDTO
mDTO --> BPM : modelPermissionDTO
deactivate mDTO
BPM --> BPS : modelPermissionDTO
deactivate BPM
end
BPS --> BC : models
deactivate BPS
BC -> BS : modelsDTO = findById(model.modelId)
activate BS
loop
BS -> BR : model = findById(modelId)
activate BR
BR -> BSchema : persistence = findOne(query)
activate BSchema
BSchema --> BR : persistence
deactivate BSchema
BR -> BM : model = toDomain(persistence)
activate BM
BM -> B : create()
activate B
B --> BM : model
deactivate B
BM --> BR : model
deactivate BM
BR --> BS : model
deactivate BR
BS -> BM : modelDTO = toDTO(model)
activate BM
BM -> DTO : create()
activate DTO
DTO --> BM : modelDTO
deactivate DTO
BM --> BS : modelDTO
deactivate BM
end
BS --> BC : modelsDTO
deactivate BS
BC --> API : modelsDTO
deactivate BC
API --> UI : modelsDTO and status

@enduml