@startuml

left to right direction
skinparam usecase {
BackgroundColor LightBlue
}

actor Médico as med
actor Paciente as pac
actor Imagiologista as img
actor Administrador as adm

adm --> (1.obter pedidos de registo)
adm --> (2.aceitar/negar pedidos de registo)
adm --> (3.obter todos os utilizadores)
med --> (7.pedir registo na plataforma)
img --> (7.pedir registo na plataforma)
med --> (8.Registar paciente)
img --> (8.Registar paciente)
med --> (9.Guardar imagens de textura)
img --> (9.Guardar imagens de textura)
med --> (11.Consultar imagens)
med --> (10.Associar imagens a paciente)
img --> (10.Associar imagens a paciente)
med --> (6.Definir que médicos podem ver as imagens)
img --> (6.Definir que médicos podem ver as imagens)
pac --> (4.Disponiblização da identificação)
pac --> (5.Obter modelos 3D pessoais)
med --> (12.Carregar modelo 3D)
med --> (13.Descarregar modelo 3D)
med --> (14.Obter modelos 3D por paciente)
med --> (15.eliminar modelo 3D)


@enduml
