@startuml

autonumber
participant "LIBCS UI" as UI
participant "LIBCS - models" as API
participant ":modelController" as BC
participant ":modelService" as BS
participant ":modelRepo" as BR
participant ":modelMap" as BM
participant ":modelDTO" as DTO
participant "m:model" as B
participant ":modelSchema" as BSchema


activate UI
activate API
UI -> API : .get('model/:patientId')
API -> BC : downloadModel(req, res, next)
activate BC
BC -> BC : patientId = req.params.patientId;
BC -> BS : models = findByPatientId(id)
activate BS
BS -> BR : models = findByPatientId(id)
activate BR
BR -> BSchema : doc = findOne(query)
activate BSchema
BSchema --> BR : persistence
deactivate BSchema
loop for each doc
BR -> BM : model = toDomain(doc)
activate BM
BM --> B : create(doc)
activate B
B --> BM : model
deactivate B
BM --> BR : model
deactivate BM
end
BR --> BS : models
deactivate BR
loop for each model
BS -> BM : modelsDTO = toDTO(model)
activate BM
BM -> DTO : create(model)
activate DTO
DTO --> BM : dto
deactivate DTO
BM --> BS : dto
end
deactivate BM
BS --> BC : modelsDTO
deactivate BS
BC --> API : models and status
deactivate BC
API --> UI : models and status

@enduml