@startuml

hide methods


package Paciente {
    entity "Paciente" as PacRoot <root> {
    } 

    class "id" as ID1 <<(v,#FF7700) identity>> <<(v,#FF7700) value object>>{}
    class "nome" as Nome1 <<(v,#FF7700) value object>>{}
    class "sns" as SNS1 <<(v,#FF7700) value object>>{}

    PacRoot --> ID1
    PacRoot --> Nome1
    PacRoot --> SNS1
}

package Imagem{
    entity "Imagem" as ImgRoot <root> {
    }

    class "id" as ID2 <<(v,#FF7700) identity>> <<(v,#FF7700) value object>>{}
    class "data" as Data1 <<(v,#FF7700) value object>>{}
    
    ImgRoot --> ID2
    ImgRoot --> Data1
}
    
package Posição {
    entity "Posição" as PosRoot <root> {
    }

    class "id" as ID3 <<(v,#FF7700) identity>> <<(v,#FF7700) value object>>{}
    class "designation" as Desc1 <<(v,#FF7700) value object>>{}

    PosRoot --> Desc1
    PosRoot --> ID3
}

package Médico {
    entity "Médico" as MedRoot <root> {
    }

    class "id" as ID4 <<(v,#FF7700) identity>> <<(v,#FF7700) value object>>{}
    class "nome" as Nome2 <<(v,#FF7700) value object>>{}
    class "password" as Pass1 <<(v,#FF7700) value object>>{}

    MedRoot --> Pass1    
    MedRoot --> Nome2
    MedRoot --> ID4
}

package Acesso_Medico_Imagem{
    entity "Acesso_Medico_Imagem" as AcessoRoot <root> {
    }

    class "id" as ID6 <<(v,#FF7700) identity>> <<(v,#FF7700) value object>>{}

    AcessoRoot --> ID6
}

package Imagiologista{
    entity "Imagiologista" as ImglRoot <root> {
    }

    class "id" as ID5 <<(v,#FF7700) identity>> <<(v,#FF7700) value object>>{}
    class "nome" as Nome3 <<(v,#FF7700) value object>>{}
    class "password" as Pass2 <<(v,#FF7700) value object>>{}

    ImglRoot --> Pass2
    ImglRoot --> Nome3
    ImglRoot --> ID5
}


PacRoot "1" <-- "n" ImgRoot : "is from a"
ImgRoot "1" --> "1" PosRoot : "has"
AcessoRoot "1" --> "1" ImgRoot : "has"
AcessoRoot "1" --> "1" MedRoot : "has"

@enduml
