@startuml
participant "LIBCS UI" as UI
participant "LIBCS - models" as API

activate UI
activate API
UI -> API : 1 : .delete(model/:id)
API -> API : 1.1 : Elimina o modelo
API --> UI : 2 : Mensagem de sucesso

@enduml