@startuml
participant "LIBCS UI" as UI
participant "LIBCS" as API

activate UI
activate API
UI -> API : 1 : .get(/request)
API -> API : 1.1 : get all user requests
API --> UI : 2 : response status

@enduml